bidd/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^cfam/',include('cfam.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'',include('biddsite.urls')),
]

biddsite/urls.py
from django.conf.urls import url
import views

app_name = 'biddsite'

urlpatterns = [
    url(r'^$',views.index,name='index'),
]

cfam/urls.py
from django.conf.urls import url
import views

app_name = 'cfam'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^molecules/?$',views.mols,name='mols'),
    url(r'^molecules/(?P<mol_id>[^/]+)/?$',views.mol,name='mol'),
    url(r'^families/?$',views.fams,name='fams'),
    url(r'^families/(?P<fam_id>[^/]+)/?$',views.fam,name='fam'),
]

biddsite/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cfam/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

# class CfamVisitLog(models.Model):
#     variable = models.CharField(max_length=20,primary_key=True)
#     value = models.IntegerField()

biddsite/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

def index(req):
    return render(req,'biddsite/index.html')

cfam/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

from django.http import Http404
from math import ceil
from conf import labels_order, ordered_labels, page_size, syn_num, mongo_mols, mongo_fams, mongo_vars 
from utils import _id2id, make_link, make_pie_json

def index(req):
    visit_count = mongo_vars.find_one_and_update({'_id':'cfam_home_visit_count'},{'$inc':{'value':1}},upsert=True,return_document=True)['value']
    return render(req,'cfam/index.html', {'visit_count': visit_count})

def mols(req):
    selected_labels = req.GET.getlist('category')
    condition = {}
    if selected_labels:
        condition = {'label':{'$in':selected_labels}}
    all_mols_num = mongo_mols.count(condition)
    max_page = int(ceil(1.0*all_mols_num/page_size))

    page = req.GET.get('page')
    page = int(page) if page else 1
    if page < 1:
        page = 1
    elif page > max_page:
        page = max_page

    mols = list(mongo_mols.find(condition,['name','label','fam_id']).skip((page-1)*page_size).limit(page_size))
    map(_id2id,mols)

    return render(req,'cfam/mols.html',{
        'labels':ordered_labels,
        'selected_labels': selected_labels,
        'page':page,
        'max_page':max_page,
        'all_mols_num':all_mols_num,
        'mols':mols,
    })

def mol(req,mol_id):
    db_mol = mongo_mols.find_one({'_id':mol_id},{'fp':0})
    if not db_mol:
        raise Http404('Molecule %s does not exist!' % mol_id)
    _id2id(db_mol)
    for src_mol in db_mol['mols']:
        if 'synonyms' in src_mol:
            synonyms = []
            count = 0
            for syn in sorted(src_mol['synonyms'],key=len):
                if count % syn_num == 0:
                    synonyms.append((count+1,[]))
                synonyms[count/syn_num][1].append(syn)
                count += 1
            src_mol['synonyms'] = synonyms
        src_mol['link'] = make_link(src_mol['src'],src_mol['src_id'])

    return render(req,'cfam/mol.html',db_mol)

def fams(req):
    selected_labels = req.GET.getlist('category')
    condition = {}
    if selected_labels:
        condition = {'label':{'$in':selected_labels}}
    all_fams_num = mongo_fams.count(condition)
    max_page = int(ceil(1.0*all_fams_num/page_size))

    page = req.GET.get('page')
    page = int(page) if page else 1
    if page < 1:
        page = 1
    elif page > max_page:
        page = max_page

    fams = list(mongo_fams.find(condition,['name','label','seeds','members']).skip((page-1)*page_size).limit(page_size))
    map(_id2id,fams)

    return render(req,'cfam/fams.html',{
        'labels':ordered_labels,
        'selected_labels': selected_labels,
        'page':page,
        'max_page':max_page,
        'all_fams_num':all_fams_num,
        'fams':fams,
    })

def fam(req,fam_id):
    db_fam = mongo_fams.find_one({'_id':fam_id},['label','seeds','members'])
    if not db_fam:
        raise Http404('Family %s does not exist!' % fam_id)
    _id2id(db_fam)
    seeds = list(mongo_mols.find({'_id':{'$in':db_fam.pop('seeds')}},['name','label']))
    map(_id2id,seeds)
    db_fam['seeds'] = sorted(seeds,key=lambda x:labels_order[x['label']])
    db_fam['pie_json'] = make_pie_json(db_fam['seeds'])
    if 'members' in db_fam:
        members = list(mongo_mols.find({'_id':{'$in':db_fam.pop('members')}},['name','label']))
        map(_id2id,members)
        db_fam['members'] = sorted(members,key=lambda x:labels_order[x['label']])

    return render(req,'cfam/fam.html',db_fam)

biddsite/templates/biddsite/index.html
go to <a href="{% url 'cfam:index' %}">Cfam</a>

cfam/templates/cfam/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="The Chemical Families Database">
  <meta name="keywords" content="chemical families,chemical family,chemical classification,chemical database">
  <meta name="author" content="He Weidong">
  <title>{% block title %}Cfam: a chemical families database{% endblock %}</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'cfam/style.css' %}"/>
  <link href="https://fonts.googleapis.com/css?family=Lato:400i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Sofadi+One" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="{% static 'cfam/main.js' %}"></script>

</head>
<body>
<header>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'cfam:index' %}">Cfam</a>
      </div>
      <!-- Items -->
      <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'cfam:mols' %}">Molecules</a></li>
              <li><a href="{% url 'cfam:fams' %}">Families</a></li>
            </ul>
          </li>
          <li><a href="#">Search</a></li>
          <li><a href="#">Download</a></li>
        </ul>
        <form class="navbar-form navbar-right" role="search" method="get" action="">
          <div class="form-group">
            <input type="text" class="form-control input-sm" name="q" value="{{req.GET.q}}" placeholder="Search">
          </div>
          <div class="form-group">
            <select name="searcher" id="searcher" class="form-control input-sm">
              <option selected="selected" value="mols">Molecules</option>
              <option value="fams">Families</option>
            </select>
          </div>
          <button type="submit" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-search"></span></button>
        </form>
      </div>
    </div>
  </nav>
</header>

<div class="container-fluid">
  {% block body %}
  {% endblock %}
</div>

<footer>
<div class="container-fluid">
  <hr>
  <div align="center" style="margin-bottom: 1em">
    A database of BIDD research group<br>
    <a href="http://bidd.nus.edu.sg" target="_blank"><img src="{% static 'biddsite/images/bidd_logo_trans.gif' %}" alt="BIDD logo"></a><br>
    12 Science Drive 2, MD1-05-03, Singapore 117549<br>
    <span class="glyphicon glyphicon-envelope"></span> <a href="mailto:phacyz@nus.edu.sg">Prof. Chen Yuzong</a>
    <span class="glyphicon glyphicon-envelope"></span> <a href="mailto:weidong@u.nus.edu">Mr. He Weidong</a>
  </div>
</div>
</footer>

</body>
</html>

cfam/templates/cfam/fam.html
{% extends 'cfam/base.html' %}
{% block title %}{{show_name}} - Cfam{% endblock %}

{% block body %}

<h1>family detail page for {{id}}</h1>

<div id="piechart" style="width: 900px; height: 500px;"></div>

<h2>seeds:</h2><br>
<div class="row">
  {% for seed in seeds %}
  <div class="col-sm-4 col-md-2">
    <div class="thumbnail">
      <div class="caption scroll-x">
        <h4>{{seed.id}}</h4>
        <h4><b>{{seed.name}}</b></h4>
        <h4>{{seed.label}}</h4>
      </div>
      <img alt="{{seed.id}}" src="http://bidd2.nus.edu.sg/static_cfam/mol_images/{{seed.id}}.png" 
      onerror="this.onerror=null;this.src='http://bidd2.nus.edu.sg/static_cfam/mol_images/{{seed.id}}.svg';">
    </div>
  </div>
  {% endfor %}
</div>

{% if members %}
<h2>members:</h2><br>
<div class="row">
  {% for member in members %}
  <div class="col-sm-4 col-md-2">
    <div class="thumbnail">
      <div class="caption scroll-x">
        <h4>{{member.id}}</h4>
        <h4><b>{{member.name}}</b></h4>
        <h4>{{member.label}}</h4>
      </div>
      <img alt="{{member.id}}" src="http://bidd2.nus.edu.sg/static_cfam/mol_images/{{member.id}}.png" 
      onerror="this.onerror=null;this.src='http://bidd2.nus.edu.sg/static_cfam/mol_images/{{member.id}}.svg';">
    </div>
  </div>
  {% endfor %}
</div>
{% endif %}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {

    var data = google.visualization.arrayToDataTable(JSON.parse('{{pie_json|safe}}'));

    var options = {
      title: 'Seeds distribution of {{show_name}}'
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart'));

    chart.draw(data, options);
  }
</script>

{% endblock %}

cfam/templates/cfam/fams.html
{% extends 'cfam/base.html' %}
{% block title %}Families - Cfam{% endblock %}

{% block body %}
<div class="well well-sm" id="filter-container">
  <form class="form-inline" action="" accept-charset="UTF-8" method="get" id="filter-form">
    <h6>Filter by category:</h6>
    <div class="filter-controls clearfix">
      {% for label in labels %}
      <div class="checkbox">
        <label><input type="checkbox" name="category" value="{{label}}" {% if label in selected_labels %}checked{% endif %}>{{label}}</label>
      </div>
      {% endfor %}
    </div>
    <h6>Jump to page:</h6>
    <input type="number" name="page" class="input-sm form-control" min="1" max="{{max_page}}" value="{{page}}">
    <div align="left" id="form-btns">
      <button type="reset" class="btn btn-default btn-xs" id="btn-clear">Clear</button>
      <button type="submit" class="btn btn-primary btn-xs">Display</button>
    </div>
  </form>
</div>

<div class="page_info" style="margin:1em 0em">Displaying page <b>{{page}} / {{max_page}}</b> of <b>{{all_fams_num}}</b> families in total</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th style="width:20%">Cfam Family ID</th>
      <th style="width:20%">Name</th>
      <th style="width:20%">Category</th>
      <th style="width:20%">Number of Seeds</th>
      <th style="width:20%">Number of Members</th>
    </tr>
  </thead>
  <tbody>
    {% for fam in fams %}
    <tr>
      <td><a href="{% url 'cfam:fam' fam.id %}" target="_blank">{{fam.id}}</a></td>
      <td>{{fam.name}}</td>
      <td>{{fam.label}}</td>
      <td>{{fam.seeds|length}}</td>
      <td>{{fam.members|length}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script type="text/javascript">
  $('#btn-clear').on('click',function() {
    var form = $(this).closest("form")
    form.find("input[type='checkbox']").attr("checked",false);
    form.find("input[type='number']").attr("value",1)
  });
</script>

{% endblock %}

cfam/templates/cfam/index.html
{% extends 'cfam/base.html' %}

{% block body %}
<main>
  <div class="container-fluid">
    <div class="well">
    <p class="lead">Cfam is a chemical family database based on molecular fingerprint similarity. The funcional seeds of families were selected by hierarchically clustering approved drugs, clinical trial drugs, experimental drugs, food ingredients or additives, human metabolites, cosmetic ingredients, agrochemicals, toxic substances, peptides, highly active molecules, mederately active molecules and natural products respectively. Cfam currently contains 1,154,416 molecules and 122,154 families.</p>
    </div>
    <div class="row" align="center">
      {{visit_count}} visits since 2017/06/28
    </div>
  </div>
</main>
{% endblock %}

cfam/templates/cfam/mol.html
{% extends 'cfam/base.html' %}
{% block title %}{{show_name}} - Cfam{% endblock %}

{% block body %}
<table class="table table-bordered table-condensed">
  <tbody>
    <tr><th class="divider" colspan="2">Record Information</th></tr>
    <tr>
      <th style="width:15%">Cfam Molecule ID</th>
      <td><strong>{{id}}</strong></td>
    </tr>
    {% if name %}<tr><th>Preferred Name</th><td><strong>{{name}}</strong></td></tr>{% endif %}
    <tr><th>Functional Category</th><td>{{label}}</td></tr>
    <tr><th>Chemical Formula</th><td>{{formula}}</td></tr>
    <tr><th>Molecular Weight</th><td>{{molwt}}</td></tr>
    {% if cid or chembl_id %}
    <tr>
      <th>External Links</th>
      <td><ul class="list-unstyled" style="margin-bottom: 0;">
        {% if cid %}<li><a href="https://pubchem.ncbi.nlm.nih.gov/compound/{{cid}}" target="_blank">PubChem CID: {{cid}}</a></li>{% endif %}
        {% if chembl_id %}<li><a href="https://www.ebi.ac.uk/chembl/compound/inspect/{{chembl_id}}" target="_blank">ChEMBLdb ID: {{chembl_id}}</a></li>{% endif %}
      </ul></td>
    </tr>
    {% endif %}
    <tr><th>Familiy Membership</th><td>A {{fam_role}} of family <a href="{% url 'cfam:fam' fam_id %}" target="_blank">{{fam_id}}</a></td></tr>
    <tr><th class="divider" colspan="2">Molecular Structure</th></tr>
    <tr>
      <th>Structure Image</th>
      <td>
        <a href="" data-target="#structure-zoom" data-toggle="modal"><img src="http://bidd2.nus.edu.sg/static_cfam/mol_images/{{id}}.png" onerror="this.onerror=null;this.src='http://bidd2.nus.edu.sg/static_cfam/mol_images/{{id}}.svg';" alt="{{id}}" style="max-height:150px;border:1px solid #dddddd"></a> (click on the thumbnail to view the full-sized image)
        <div class="modal fade" id="structure-zoom">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button aria-hidden="true" class="close" data-dismiss="modal" type="button"> ×</button>
                <h4 class="modal-title">Structure of {{show_name}}</h4></div>
              <div class="modal-body">
                <img src="http://bidd2.nus.edu.sg/static_cfam/mol_images/{{id}}.png" onerror="this.onerror=null;this.src='http://bidd2.nus.edu.sg/static_cfam/mol_images/{{id}}.svg';" alt="{{id}}">
              </div>
              <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" type="button"> Close</button>
              </div>
            </div>
          </div>
        </div>
      </td>
    </tr>
    <tr><th>SMILES</th><td>{{smi}}</td></tr>
    <tr><th>InChI</th><td>{{inchi}}</td></tr>
    <tr><th>InChIKey</th><td>{{inchikey}}</td></tr>
  </tbody>
</table>

<h3>Sources</h3>
<div class="well well-sm" style="background: #B2D0B4;">
  {% for src_mol in mols %}
  <div class="panel panel-default">
    <div class="panel-heading"><strong>{{forloop.counter}}. <a href="{{src_mol.link}}" target="_blank">{{src_mol.src}}: {{src_mol.src_id}}</a></strong></div>
    <div class="panel-body">
      <dl class="dl-horizontal">
        {% if src_mol.name %}<dt>Name</dt><dd>{{src_mol.name}}</dd>{% endif %}
        <dt>Functional Category</dt><dd>{{src_mol.category|join:"; "}}</dd>
        {% if src_mol.synonyms %}
        <dt>Synonyms</dt>
        <dd>
          <div class="scroll-x" style="border:1px solid #dddddd;border-radius:5px;padding:0.5em;margin-top:0.5em">
            <div style="display:table;" >
              {% for syn_list in src_mol.synonyms %}
              <ol start="{{syn_list.0}}" style="display:table-cell;">
                {% for syn in syn_list.1 %}
                <li>{{syn}}</li>
                {% endfor %}
              </ol>
              {% endfor %}
            </div>
          </div>
        </dd>
        {% endif %}
      </dl>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

cfam/templates/cfam/mols.html
{% extends 'cfam/base.html' %}
{% block title %}Molecules - Cfam{% endblock %}

{% block body %}
<div class="well well-sm" id="filter-container">
  <form class="form-inline" action="" accept-charset="UTF-8" method="get" id="filter-form">
    <h6>Filter by category:</h6>
    <div class="filter-controls clearfix">
      {% for label in labels %}
      <div class="checkbox">
        <label><input type="checkbox" name="category" value="{{label}}" {% if label in selected_labels %}checked{% endif %}>{{label}}</label>
      </div>
      {% endfor %}
    </div>
    <h6>Jump to page:</h6>
    <input type="number" name="page" class="input-sm form-control" min="1" max="{{max_page}}" value="{{page}}">
    <div align="left" id="form-btns">
      <button type="reset" class="btn btn-default btn-xs" id="btn-clear">Clear</button>
      <button type="submit" class="btn btn-primary btn-xs">Display</button>
    </div>
  </form>
</div>

<div class="page_info" style="margin:1em 0em">Displaying page <b>{{page}} / {{max_page}}</b> of <b>{{all_mols_num}}</b> molecules in total</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th style="width:20%">Cfam Molecule ID</th>
      <th style="width:20%">Name</th>
      <th style="width:20%">Category</th>
      <th style="width:20%">Structure</th>
      <th style="width:20%">Family</th>
    </tr>
  </thead>
  <tbody>
    {% for mol in mols %}
    <tr>
      <td><a href="{% url 'cfam:mol' mol.id %}" target="_blank">{{mol.id}}</a></td>
      <td>{{mol.name}}</td>
      <td>{{mol.label}}</td>
      <td>
        <img src="http://bidd2.nus.edu.sg/static_cfam/mol_images/{{mol.id}}.png" onerror="this.onerror=null;this.src='http://bidd2.nus.edu.sg/static_cfam/mol_images/{{mol.id}}.svg';" alt="{{mol.id}}" style="max-height:150px;border:1px solid #dddddd">
      </td>
      <td><a href="{% url 'cfam:fam' mol.fam_id %}" target="_blank">{{mol.fam_id}}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script type="text/javascript">
  $('#btn-clear').on('click',function() {
    var form = $(this).closest("form")
    form.find("input[type='checkbox']").attr("checked",false);
    form.find("input[type='number']").attr("value",1)
  });
</script>

{% endblock %}